(()=>{'use strict';const $=id=>document.getElementById(id);let setup=false,content,catalog,current,dirty=false;const notify=t=>$('message').textContent=t;
async function api(route,method='GET',body){const r=await fetch('/api/'+route,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'操作失败');return data}
async function start(){const s=await api('status');setup=s.needsSetup;$('loginTitle').textContent=setup?'设置你的管理密码':'登录';$('setupNote').hidden=!setup;$('password').minLength=setup?12:1;$('password').autocomplete=setup?'new-password':'current-password';$('login').hidden=s.authenticated;$('editor').hidden=!s.authenticated;if(s.authenticated)await load()}
$('login').onsubmit=async e=>{e.preventDefault();try{await api(setup?'setup':'login','POST',{password:$('password').value});$('password').value='';notify('已登录');await start()}catch(e){notify(e.message)}};
function field(label,value,id,parent,type='input'){const l=document.createElement('label');l.textContent=label;const input=document.createElement(type);input.id=id;input.value=value;l.append(input);parent.append(l)}
async function load(){[content,catalog]=await Promise.all([api('content'),api('catalog')]);for(const k of ['name','intro','portrait'])$(k).value=content.profile[k]||'';$('name').placeholder='Alkaid';$('intro').placeholder='留空时使用原有个人简介';$('workTitle').value=content.works.title;$('subtitle').value=content.works.subtitle;$('description').value=content.works.description;$('chapters').replaceChildren();content.works.chapters.forEach((c,i)=>{const f=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent='第'+(i+1)+'章';f.append(legend);field('标题',c.title,'chapter-title-'+i,f);field('简介',c.summary,'chapter-summary-'+i,f,'textarea');field('目录：每行一条',c.sections.join('\n'),'chapter-sections-'+i,f,'textarea');$('chapters').append(f)});$('musicEnabled').checked=content.music.enabled;$('album').value='https://open.spotify.com/album/'+content.music.albumId;$('musicTitle').value=content.music.title;$('artist').value=content.music.artist;$('node').replaceChildren();for(const n of catalog.nodes){const o=document.createElement('option');o.value=n.id;o.textContent=n.name+' · '+n.year;$('node').append(o)}current=null;showNode();dirty=false}
function stashNode(){if(!current)return;const edit={};for(const [key,id] of [['book','book'],['url','url'],['intro','nodeIntro'],['claim','claim']])edit[key]=$(id).value;edit.guide={};for(const lang of ['zh','en','ja','ko'])edit.guide[lang]=$('guide-'+lang).value;content.nodeEdits[current]=edit}
function showNode(){current=$('node').value;const n=catalog.nodes.find(n=>n.id===current),e=content.nodeEdits[current]||{};for(const [key,id] of [['book','book'],['url','url'],['intro','nodeIntro'],['claim','claim']])$(id).value=e[key]??n[key];for(const lang of ['zh','en','ja','ko'])$('guide-'+lang).value=e.guide?.[lang]??catalog.guides[current]?.[lang]??''}
$('node').onchange=()=>{stashNode();showNode()};$('editor').oninput=()=>{dirty=true};
$('editor').onsubmit=async e=>{e.preventDefault();try{stashNode();content.profile={};for(const k of ['name','intro','portrait'])if($(k).value.trim())content.profile[k]=$(k).value.trim();content.works.title=$('workTitle').value;content.works.subtitle=$('subtitle').value;content.works.description=$('description').value;content.works.chapters.forEach((c,i)=>{c.title=$('chapter-title-'+i).value;c.summary=$('chapter-summary-'+i).value;c.sections=$('chapter-sections-'+i).value.split('\n').map(s=>s.trim()).filter(Boolean)});const album=new URL($('album').value);if(album.hostname!=='open.spotify.com'||!/^\/album\/[A-Za-z0-9]{22}\/?$/.test(album.pathname))throw Error('请填入 Spotify 专辑页面链接');content.music={enabled:$('musicEnabled').checked,albumId:album.pathname.split('/')[2],title:$('musicTitle').value,artist:$('artist').value};await api('content','PUT',content);dirty=false;notify('已保存到本机网站。刷新预览查看；上线需同步这些改动到你的仓库。')}catch(e){notify(e.message)}};
$('logout').onclick=async()=>{if(dirty&&!confirm('尚有未保存修改，仍然退出？'))return;await api('logout','POST',{});dirty=false;location.reload()};window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});start().catch(e=>notify(e.message));})();
